// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  app: string;
  previewView: string;
}
export const cssExports: CssExports;
export default cssExports;
